---
title: "How can Quarto documents help with reproducibility in research?"
author: "Håkon Ivesdal"
date: last-modified
date-format: "dddd D MMM, YYYY"
csl: apa7.csl
lang: en-US
format:
  html: default
  pdf:
    documentclass: article
    number-sections: true
    keep-tex: true
    papersize: A4
    fig-pos: "H"
bibliography: reproducibility.bib
abstract: "There is a recent reproducibility crisis in research. Quarto documents can help by enhancing reproducibility in research by integrating code and data directly in the document. The Quarto document could then be the entire submission to the journals."
---

## Introduction

Scientific progress relies on the generation of robust, reliable knowledge that provides a solid foundation for future advancements.
There is strong evidence suggesting that many of these findings may not endure over time.
This reproducibility crisis in basic and preclinical research is largely attributed to a lack of adherence to proper scientific practices, compounded by the pressure to "publish or perish" [@begley2015].
Reproducing an experiment is a key method scientists use to strengthen confidence in their conclusions and data handling is an important part of it [@mcnutt2014].

Unfortunately the long-established archives at economics journals do not effectively support the reproduction of published results.
Data-only archives, like those of the Journal of Business and Economic Statistics and the Economic Journal, are limited in part because many authors do not provide their data.
Similarly, results published in the FRB St. Louis Review are rarely reproducible, even when data and code are included in the journal's archive [@mccullough2008].

## Terminology

Reproduce and replicate have been used differently and indifferently from one and another, depending on the situation and the field.
Normally to suggest a form of duplication of a study.
In computational fields, reproducibility typically refers to the ability to reproduce computational results, focusing specifically on sharing and properly documenting data and code [@peng2011].

When people refer to a "replication," they may mean one of the following: duplicating the methods, procedures, and analysis of a study (regardless of the outcomes) or duplicating the methods, procedures, analysis, and the results themselves [@fidler2021].
It is implied that the new data set determine the outcome as the other variables are constant.
These meanings describes two of the three parts that make up Research reproducibility.
The former describes Methods reproducibility, while the latter describes Results reproducibility.
Robustness and generalizability is the third part and takes into account the difference that outside effects have on the experimental framework's setting [@goodman2016].

The NSF (Subcommittee on Replicability in Science Advisory Committee to the National Science Foundation Directorate for Social, Behavioural, and Economic Sciences) defines Methods reproducibility simply as Reproducibility and Results reproducibility as Replicability [@bollen2015].
This is also how it will be referred to in the rest of the paper.

## How can Quarto documents help with reproducibility?

Reproducibility is a precursor to achieving replicability, but it can be challenging to attain.
Reproducibility demands that the code and data used to generate a manuscript is fully integrated into it [@zotero-97].
In traditional documents third party software are used to make the different models and calculations.
R Markdown, which Quarto is based on, enables the creation of computationally reproducible documents by allowing authors to embed R code for data processing, analysis, exploration, table generation, and visualization directly into structured electronic documents.
These documents consist of sections of R code, referred to as computational components because they are produced through computational methods, along with narrative components.
In scientific writing, these narrative sections provide context, explain background, define objectives, set themes, and communicate results.
The documents can then be rendered into formats such as .html, .pdf, .doc [@grolemunda].

Quarto is the next generation version of R Markdown, without relying or requiring R.
Designed to be a multilingual tool from the start, by supporting languages such as R, Python, JavaScript, and Julia, with the goal of being adaptable to future programming languages that may emerge in the future [@zotero-84].
A key part of the adaptability and functionality of Quarto documents are called packages and could remove the need for third party applications.
Packages are collections of functions, data, and compiled code [@zotero-101].
Some of these extensions are default or downloadable in the integrated development environment called RStudio [@zotero-103].

By integrating every part of the work after data extraction, the entire entry to a Journal could just be one Quarto document.
This would ease the process of achieving the same results and be a helpful step towards replication.

### What problems remains and how can these be solved?

Quarto documents are fully reproducible [@wickham2019], assuming hardware and software is accounted for.
It is therefore important to document hardware, system, system-libraries, R-version and package-versions.
The first four are relative easily done by using the built-in function: "sessionInfo()".
However the packages are constantly updated and could be updated under the development of the document.
A solution to this problem is a package in RStudio called renv.
It enables the creation of reproducible environments for R projects, ensuring consistent dependencies and package versions across different systems.
Each project is given its own private package library, meaning that installing or updating a package for one project won't affect the other projects [@ushey].

## Conclusion

The ability to reproduce results is foundational to scientific research and replication.
By embedding code and data directly within the document, Quarto can ensure that the methods, analyses and calculation used to generate results are transparent and easily accessible.
While it cannot retrospectively fix past entries, it can pave the way for more reliable published research findings in the future.

## References
